//
// Generated by ATOM Flag Preprocessor:  Tue Oct  8 13:51:20 2024
//

#ifndef ATOM_FLAGS_H
#define ATOM_FLAGS_H

#include <stdbool.h>

typedef struct FlagInfo {
    const char* flag_name;
    bool default_value;
} FlagInfo;

enum ATOM_CT__FLAGS {
    ATOM_CT__FLAG_COUNT
};

enum ATOM_CT__OPTIONS {
    ATOM_CT__OPTION_COUNT
};

extern bool ATOM_VR__FLAGS[ATOM_CT__FLAG_COUNT];
extern FlagInfo ATOM_CT__FLAGINFO[ATOM_CT__FLAG_COUNT];

#endif //ATOM_FLAGS_H