//
// Generated by ATOM Flag Preprocessor:  10/09/24 00:07:47
//

#ifndef ATOM_FLAGS_H
#define ATOM_FLAGS_H

#include <stdbool.h>

typedef struct FlagInfo {
    const char* flag_name;
    bool default_value;
} FlagInfo;

enum ATOM_CT__FLAGS {
    ATOM_CT__FLAG_AST_OUT,
    ATOM_CT__FLAG_EXPR_DBG,
    ATOM_CT__FLAG_FLAGS_OUT,
    ATOM_CT__FLAG_HADRON_VERIFY,
    ATOM_CT__FLAG_SCOPE_OUT,
    ATOM_CT__FLAG_TOK_OUT,
    ATOM_CT__FLAG_VEXPR_DBG,
    ATOM_CT__FLAG_VLTOK_OUT,
    ATOM_CT__FLAG_VTOK_OUT,
    ATOM_CT__FLAG_COUNT
};

enum ATOM_CT__OPTIONS {
    ATOM_CT__OPTION_O,
    ATOM_CT__OPTION_OUT,
    ATOM_CT__OPTION_OUTPUT,
    ATOM_CT__OPTION_E,
    ATOM_CT__OPTION_Entry,
    ATOM_CT__OPTION_DEBUGLVL,
    ATOM_CT__OPTION_LVL,
    ATOM_CT__OPTION_COUNT
};

extern bool ATOM_VR__FLAGS[ATOM_CT__FLAG_COUNT];
extern FlagInfo ATOM_CT__FLAGINFO[ATOM_CT__FLAG_COUNT];

#endif //ATOM_FLAGS_H