//
// Generated by ATOM Flag Preprocessor: Thu Oct 17 12:42:43 2024
//

#ifndef ATOM_FLAGS_H
#define ATOM_FLAGS_H

#include <stdbool.h>
#include "FlagPreprocessorInject.h"
#include "Vector.h"

enum ATOM_CT__FLAGS {
    ATOM_CT__FLAG_AST_OUT,
    ATOM_CT__FLAG_EXPR_DBG,
    ATOM_CT__FLAG_FLAGS_OUT,
    ATOM_CT__FLAG_HADRON_VERIFY,
    ATOM_CT__FLAG_SCOPE_OUT,
    ATOM_CT__FLAG_TOK_OUT,
    ATOM_CT__FLAG_VEXPR_DBG,
    ATOM_CT__FLAG_VLTOK_OUT,
    ATOM_CT__FLAG_VTOK_OUT,
    ATOM_CT__FLAG_COUNT
};

enum ATOM_CT__OPTIONS {
    ATOM_CT__OPTION_DEBUGLVL,
    ATOM_CT__OPTION_E,
    ATOM_CT__OPTION_O,
    ATOM_CT__OPTION_OUT,
    ATOM_CT__OPTION_TEST,
    ATOM_CT__OPTION_COUNT
};

extern bool ATOM_VR__FLAGS[ATOM_CT__FLAG_COUNT];
extern const FlagInfo ATOM_CT__FLAGINFO[ATOM_CT__FLAG_COUNT];
extern const StaticOptionInfo ATOM_CT__OPTIONINFO[ATOM_CT__OPTION_COUNT];

#endif //ATOM_FLAGS_H