<letter> ::= a | b | c | d | e | f | g | h | i | j | k | l | m | n | o | p
            | q | r | s | t | u | v | w | x | y | z | A | B | C | D | E | F
            | G | H | I | J | K | L | M | N | O | P | Q | R | S | T | U | V
            | W | X | Y | Z
<digit> ::= 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
<number> ::= <digit> | <number> <digit>
<integer> ::= <number> | '-' <number>
<real> ::= <number> '.' <number> | <number> '.' | '.' <number>

<variable name> ::= letter | <variable name> <letter> | <variable name> digit | <variable name> '_'

<type> ::= i1 | i2 | i4 | i8 | n1 | n2 | n4 | n8 | r4 | r8 | q4 | q8 | q16 | string | bool | char | nav

<variable declaration>  ::= <variable name> ':' <type>
<variable creation> ::= <variable declaration> '=' <value> | <variable declaration>
<variable assignment> ::= <variable name> '=' <value>

<declaration statement> ::= <variable creation> | <variable assignment> | <variable declaration> | <variable name>

<comparison op> ::= '<' | '>' | '<=' | '>=' | '==' | '!='
<comparison statement> ::= <value> <comparison op> <value>

<arithmetic assignment op> ::= '+=' | '-=' | '*=' | '/=' | '%='
<arithmetic assignment statement> ::= <variable name> <arithmetic assignment op> <value>

<arithmetic op> ::= '+' | '-' | '*' | '/' | '%' | '^' | '<<' | '>>'
<arithmetic statement> ::= <value> <arithmetic op> <value>

<value> ::= <variable name> |

<for statement> ::= "for" <declaration statement> "to" (<value>|<comparison statement>) ("do" <arithmetic assignment statement>)?

