#include "../TypePreprocessor/enum-out.h"

const char* ATOM_CT__LEX_TYPES_RAW[] = {
    "bool", 
    "chr", 
    "func", "proc", 
    "i1", "i2", "i4", "i8", 
    "n1", "n2", "n4", "n8", 
    "q4", "q8", "q16", 
    "r4", "r8", "r10", 
    "str", 
    "struct", 
    "void", 
};

const char* ATOM_CT__LEX_TYPES_GENERAL_RAW[]= {
    "POINTER",
    "BOOLEAN",
    "CHAR",
    "FUNCTION",
    "INTEGER",
    "NATURAL",
    "RATIONAL",
    "REAL",
    "STRING",
    "STRUCT",
    "VOID"
};

const char* ATOM_CT__LEX_TYPES_GENERAL_SMALL_RAW[]= {
    "ptr",
    "bool",
    "chr",
    "func","proc",
    "i",
    "n",
    "q",
    "r",
    "str",
    "struct",
    "void"
};

const char* ATOM_CT__LEX_OPERATORS_RAW[]= {
    "&",
    "->",
    "=",
    "&=",
    "|=",
    "/=",
    "-=",
    "%=",
    "*=",
    "+=",
    "^=",
    "<<=",
    ">>=",
    "&",
    "~",
    "|",
    "|-",
    "--",
    "*",
    "/",
    "==",
    "++",
    "&&",
    "<",
    "<=",
    "!",
    "||",
    "|-|",
    "-",
    "%",
    ">",
    ">=",
    "*",
    "!=",
    "+",
    "^",
    "..",
    "<<",
    ">>",
    "<>",
    "as"
};

OpInfo OP_INFO[41]= {
    [OP_AMPERSAND]=  (OpInfo){.precedence=5,.assoc=0,.type=0},
    [OP_ARROW]=      (OpInfo){5, 0, 3},
    [OP_ASSIGN]=     (OpInfo){5, 0, 3},
    [OP_ASS_BAND]=   (OpInfo){5, 0, 3},
    [OP_ASS_BOR]=    (OpInfo){5, 0, 3},
    [OP_ASS_DIV]=    (OpInfo){5, 0, 3},
    [OP_ASS_MINUS]=  (OpInfo){5, 0, 3},
    [OP_ASS_MOD]=    (OpInfo){5, 0, 3},
    [OP_ASS_MULT]=   (OpInfo){5, 0, 3},
    [OP_ASS_PLUS]=   (OpInfo){5, 0, 3},
    [OP_ASS_POW]=    (OpInfo){5, 0, 3},
    [OP_ASS_SHL]=    (OpInfo){5, 0, 3},
    [OP_ASS_SHR]=    (OpInfo){5, 0, 3},
    [OP_BAND]=       (OpInfo){5, 0, 3},
    [OP_BNOT]=       (OpInfo){5, 0, 0},
    [OP_BOR]=        (OpInfo){5, 0, 3},
    [OP_BXOR]=       (OpInfo){5, 0, 3},
    [OP_DEC]=        (OpInfo){5, 0, 2},
    [OP_DEREF]=      (OpInfo){5, 0, 0},
    [OP_DIV]=        (OpInfo){5, 0, 3},
    [OP_EQU]=        (OpInfo){5, 0, 3},
    [OP_INC]=        (OpInfo){5, 0, 2},
    [OP_LAND]=       (OpInfo){5, 0, 3},
    [OP_LESS]=       (OpInfo){5, 0, 3},
    [OP_LESSEQ]=     (OpInfo){5, 0, 3},
    [OP_LNOT]=       (OpInfo){5, 0, 0},
    [OP_LOR]=        (OpInfo){5, 0, 3},
    [OP_LXOR]=       (OpInfo){5, 0, 3},
    [OP_MINUS]=      (OpInfo){5, 0, 3},
    [OP_MOD]=        (OpInfo){5, 0, 3},
    [OP_MORE]=       (OpInfo){5, 0, 3},
    [OP_MOREEQ]=     (OpInfo){5, 0, 3},
    [OP_MULT]=       (OpInfo){5, 0, 3},
    [OP_NEQ]=        (OpInfo){5, 0, 3},
    [OP_PLUS]=       (OpInfo){5, 0, 3},
    [OP_POW]=        (OpInfo){5, 0, 3},
    [OP_RANGE]=      (OpInfo){5, 0, 3},
    [OP_SHL]=        (OpInfo){5, 0, 3},
    [OP_SHR]=        (OpInfo){5, 0, 3},
    [OP_SWAP]=       (OpInfo){5, 0, 3},
    [OP_TYPE_CONV]=  (OpInfo){5, 0, 3}
};

