//
// Created by jamescoward on 10/06/2025.
//

#ifndef ATOMIC_TPPGENERATORINTERNAL_H
#define ATOMIC_TPPGENERATORINTERNAL_H

#define OP_ENUM_PREFIX      "OP_"
#define TYPE_ENUM_PREFIX    "TYPE_"
#define GENERAL_ENUM_PREFIX "GTYPE_"

#define TYPES_ARRAY_NAME        "ATOM_CT__LEX_TYPES_RAW"
#define GENERAL_ARRAY_NAME      "ATOM_CT__LEX_TYPES_GENERAL_RAW"
#define TYPES_SMALL_ARRAY_NAME  "ATOM_CT__LEX_TYPES_GENERAL_SMALL_RAW"

#define OP_ARRAY_NAME       "ATOM_CT__LEX_OPERATORS_RAW"

#define OP_INFO_ARRAY_NAME  "OP_INFO"

#endif // ATOMIC_TPPGENERATORINTERNAL_H
